CLASS ZTP_bp_bookingsupplement_u DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF ZTP_i_travel_u .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZTP_bp_bookingsupplement_u IMPLEMENTATION.
ENDCLASS.
