"! @testing ZTP_CL_I_TRAVEL_TUM
"! @testing ZTP_CL_C_TRAVEL_TUM
"! @testing ZTP_CL_FLIGHT_LEGACY
"! @testing FUGR:ZTP_FLIGHT_TRAVEL_API
CLASS ltc DEFINITION FINAL INHERITING FROM ZTP_tc_flight_travel_api FOR TESTING RISK LEVEL HARMLESS DURATION MEDIUM.
ENDCLASS.
